[build]
target = "x86_64-unknown-linux-gnu"

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C",
    "link-arg=-nostartfiles",
    "-C",
    "link-arg=-nodefaultlibs",
    "-C",
    "link-arg=-nostdlib",
    "-C",
    "link-arg=-e",
    "-C",
    "link-arg=start",
    "-C",
    "link-arg=-T",
    "-C",
    "link-arg=linker.ld",
    "-C",
    "link-arg=--no-undefined",
    "-C",
    "link-arg=--build-id=none",
]
